// @ts-nocheck
import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { Providers } from "@/providers";

export const metadata: Metadata = {
  title: "Nextkit App",
  description: "Generated by Nextkit",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <Providers>
        <body>{children}</body>
      </Providers>
    </html>
  );
}
